### ISSUE TITLE
[BUG] Error while installing hashicorp/azurerm v3.55.0: read tcp 100.107.17.10:56411->18.164.52.95:443: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by getwebem** [claranet/terraform-azurerm-expressroute#1]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1

### AzureRM Provider Version

v3.55.0

### Affected Resource(s)/Data Source(s)

dont know

### Terraform Configuration Files

```hcl
terraform init
```

### Debug Output/Panic Output

```shell
│ Error: Failed to install provider
│
│ Error while installing hashicorp/azurerm v3.55.0: read tcp 100.107.17.10:56411->18.164.52.95:443: wsarecv: An existing connection was forcibly closed by the remote host.
```

### Expected Behaviour

should show me green sign for the next command 

### Actual Behaviour

error

### Steps to Reproduce

terraform init

### Important Factoids

none

### References

![Screenshot (115)](https://github.com/claranet/terraform-azurerm-expressroute/assets/15692073/0e77a7d3-1b47-4d35-bbbb-51000c6f4363)

**Comment by jmapro** [comment]
Hi !

This is not related to the module. It's an error between your computer and hashicorp registry.

Jeremy.
